# Quality

In [1]:
import tensorflow as tf
from keras import backend as K

import os
from keras.models import Model
from tensorflow.keras.optimizers import Adam
from keras.applications.vgg16 import VGG16, preprocess_input
from keras.preprocessing.image import ImageDataGenerator
from keras.callbacks import ModelCheckpoint, EarlyStopping
from keras.layers import Dense, Dropout, Flatten
from pathlib import Path
import numpy as np

### Load model

In [2]:
quality_model_file = f'model_quality'
# /tl-vgg16-rms-prop-model_*
model_quality_path = Path(quality_model_file)

In [3]:
for model_name in model_quality_path.glob('*model_*'):
    print(model_name.name)

tl-vgg16-rms-prop-model_02.h5
tl-vgg16-rms-prop-model_04.h5
tl-vgg16-rms-prop-model_15.h5
tl-vgg16-rms-prop-model_13.h5
tl-vgg16-rms-prop-model_11.h5
tl-vgg16-rms-prop-model_05.h5
tl-vgg16-rms-prop-model_10.h5
tl-vgg16-rms-prop-model_09.h5
tl-vgg16-rms-prop-model_07.h5
tl-vgg16-rms-prop-model_12.h5
tl-vgg16-rms-prop-model_14.h5
tl-vgg16-rms-prop-model_17.h5
tl-vgg16-rms-prop-model_19.h5
tl-vgg16-rms-prop-model_06.h5
tl-vgg16-rms-prop-model_20.h5
tl-vgg16-rms-prop-model_03.h5
tl-vgg16-rms-prop-model_18.h5
tl-vgg16-rms-prop-model_08.h5
tl-vgg16-rms-prop-model_01.h5
tl-vgg16-rms-prop-model_16.h5


In [2]:
def evaluate(model_name, imgen, batch_size=32):
    from sklearn.metrics import classification_report, confusion_matrix
    
    base_model = keras.models.load_model(model_name)
#     base_model.summary()
    base_model.trainable = False
    model = base_model
    model.compile(optimizer=keras.optimizers.RMSprop(),
              loss=keras.losses.CategoricalCrossentropy(),
              metrics=[keras.metrics.CategoricalAccuracy()])
    classes = imgen.class_indices
    class_list = ['']*len(classes)
    for k, v in classes.items():
        class_list[v] = k
    num_of_test_samples = len(imgen.classes)
    batch_size = batch_size
    #Confution Matrix and Classification Report
    Y_pred = model.predict_generator(imgen, num_of_test_samples)
    print(Y_pred)
    y_pred = np.argmax(Y_pred, axis=1)
#     print(y_pred)
#     print(imgen.classes)
    print('Confusion Matrix')
    print(confusion_matrix(imgen.classes, y_pred))
    print('Classification Report')
    target_names = class_list
    print(classification_report(imgen.classes, y_pred, target_names=target_names))

### Load data

In [23]:
BATCH_SIZE = 10
test_data_dir = f'fruit_data_quality/Test'
test_generator = ImageDataGenerator(preprocessing_function=preprocess_input)
testgen = test_generator.flow_from_directory(test_data_dir,
                                             target_size=(224, 224),
                                             class_mode='categorical',
                                             batch_size=BATCH_SIZE,
                                             shuffle=False,
                                             seed=42)

Found 3691 images belonging to 2 classes.


### Evaluate

In [24]:
import keras
quality_model_file = f'model_quality'
model_quality_path = Path(quality_model_file)
for model_name in model_quality_path.glob('*model_*'):
    print(model_name.name)
    evaluate(model_name=model_name, imgen=testgen, batch_size=BATCH_SIZE)

tl-vgg16-rms-prop-model_02.h5


/tmp/ipykernel_52851/2584673372.py:18: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  Y_pred = model.predict_generator(imgen, num_of_test_samples)


[[9.9999994e-01 0.0000000e+00]
 [9.9999994e-01 1.4997924e-15]
 [0.0000000e+00 9.9999994e-01]
 ...
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]]
Confusion Matrix
[[ 876  482]
 [   2 2331]]
Classification Report
              precision    recall  f1-score   support

         Bad       1.00      0.65      0.78      1358
        Good       0.83      1.00      0.91      2333

    accuracy                           0.87      3691
   macro avg       0.91      0.82      0.84      3691
weighted avg       0.89      0.87      0.86      3691

tl-vgg16-rms-prop-model_04.h5


/tmp/ipykernel_52851/2584673372.py:18: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  Y_pred = model.predict_generator(imgen, num_of_test_samples)


[[0.99999994 0.        ]
 [0.99999994 0.        ]
 [0.         0.99999994]
 ...
 [0.         1.        ]
 [0.         1.        ]
 [0.         1.        ]]
Confusion Matrix
[[ 760  598]
 [   1 2332]]
Classification Report
              precision    recall  f1-score   support

         Bad       1.00      0.56      0.72      1358
        Good       0.80      1.00      0.89      2333

    accuracy                           0.84      3691
   macro avg       0.90      0.78      0.80      3691
weighted avg       0.87      0.84      0.82      3691

tl-vgg16-rms-prop-model_15.h5


/tmp/ipykernel_52851/2584673372.py:18: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  Y_pred = model.predict_generator(imgen, num_of_test_samples)


[[0.99999994 0.        ]
 [0.99999994 0.        ]
 [0.         0.99999994]
 ...
 [0.         1.        ]
 [0.         1.        ]
 [0.         1.        ]]
Confusion Matrix
[[ 894  464]
 [   1 2332]]
Classification Report
              precision    recall  f1-score   support

         Bad       1.00      0.66      0.79      1358
        Good       0.83      1.00      0.91      2333

    accuracy                           0.87      3691
   macro avg       0.92      0.83      0.85      3691
weighted avg       0.89      0.87      0.87      3691

tl-vgg16-rms-prop-model_13.h5


/tmp/ipykernel_52851/2584673372.py:18: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  Y_pred = model.predict_generator(imgen, num_of_test_samples)


[[0.99999994 0.        ]
 [0.         0.99999994]
 [0.         0.99999994]
 ...
 [0.         1.        ]
 [0.         1.        ]
 [0.         1.        ]]
Confusion Matrix
[[ 788  570]
 [   0 2333]]
Classification Report
              precision    recall  f1-score   support

         Bad       1.00      0.58      0.73      1358
        Good       0.80      1.00      0.89      2333

    accuracy                           0.85      3691
   macro avg       0.90      0.79      0.81      3691
weighted avg       0.88      0.85      0.83      3691

tl-vgg16-rms-prop-model_11.h5


/tmp/ipykernel_52851/2584673372.py:18: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  Y_pred = model.predict_generator(imgen, num_of_test_samples)


[[0.99999994 0.        ]
 [0.         0.99999994]
 [0.         0.99999994]
 ...
 [0.         1.        ]
 [0.         1.        ]
 [0.         1.        ]]
Confusion Matrix
[[ 717  641]
 [   1 2332]]
Classification Report
              precision    recall  f1-score   support

         Bad       1.00      0.53      0.69      1358
        Good       0.78      1.00      0.88      2333

    accuracy                           0.83      3691
   macro avg       0.89      0.76      0.78      3691
weighted avg       0.86      0.83      0.81      3691

tl-vgg16-rms-prop-model_05.h5


/tmp/ipykernel_52851/2584673372.py:18: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  Y_pred = model.predict_generator(imgen, num_of_test_samples)


[[9.9999994e-01 0.0000000e+00]
 [9.9999994e-01 1.3694469e-23]
 [0.0000000e+00 9.9999994e-01]
 ...
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]]
Confusion Matrix
[[ 804  554]
 [   1 2332]]
Classification Report
              precision    recall  f1-score   support

         Bad       1.00      0.59      0.74      1358
        Good       0.81      1.00      0.89      2333

    accuracy                           0.85      3691
   macro avg       0.90      0.80      0.82      3691
weighted avg       0.88      0.85      0.84      3691

tl-vgg16-rms-prop-model_10.h5


/tmp/ipykernel_52851/2584673372.py:18: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  Y_pred = model.predict_generator(imgen, num_of_test_samples)


[[0.99999994 0.        ]
 [0.         0.99999994]
 [0.         0.99999994]
 ...
 [0.         1.        ]
 [0.         1.        ]
 [0.         1.        ]]
Confusion Matrix
[[ 757  601]
 [   1 2332]]
Classification Report
              precision    recall  f1-score   support

         Bad       1.00      0.56      0.72      1358
        Good       0.80      1.00      0.89      2333

    accuracy                           0.84      3691
   macro avg       0.90      0.78      0.80      3691
weighted avg       0.87      0.84      0.82      3691

tl-vgg16-rms-prop-model_09.h5


/tmp/ipykernel_52851/2584673372.py:18: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  Y_pred = model.predict_generator(imgen, num_of_test_samples)


[[9.9999994e-01 0.0000000e+00]
 [5.8903633e-14 9.9999994e-01]
 [0.0000000e+00 9.9999994e-01]
 ...
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]]
Confusion Matrix
[[ 777  581]
 [   0 2333]]
Classification Report
              precision    recall  f1-score   support

         Bad       1.00      0.57      0.73      1358
        Good       0.80      1.00      0.89      2333

    accuracy                           0.84      3691
   macro avg       0.90      0.79      0.81      3691
weighted avg       0.87      0.84      0.83      3691

tl-vgg16-rms-prop-model_07.h5


/tmp/ipykernel_52851/2584673372.py:18: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  Y_pred = model.predict_generator(imgen, num_of_test_samples)


[[9.9999994e-01 0.0000000e+00]
 [2.2721164e-25 9.9999994e-01]
 [0.0000000e+00 9.9999994e-01]
 ...
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]]
Confusion Matrix
[[ 798  560]
 [   0 2333]]
Classification Report
              precision    recall  f1-score   support

         Bad       1.00      0.59      0.74      1358
        Good       0.81      1.00      0.89      2333

    accuracy                           0.85      3691
   macro avg       0.90      0.79      0.82      3691
weighted avg       0.88      0.85      0.84      3691

tl-vgg16-rms-prop-model_12.h5


/tmp/ipykernel_52851/2584673372.py:18: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  Y_pred = model.predict_generator(imgen, num_of_test_samples)


[[9.9999994e-01 0.0000000e+00]
 [1.2115096e-31 9.9999994e-01]
 [0.0000000e+00 9.9999994e-01]
 ...
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]
 [0.0000000e+00 1.0000000e+00]]
Confusion Matrix
[[ 845  513]
 [   0 2333]]
Classification Report
              precision    recall  f1-score   support

         Bad       1.00      0.62      0.77      1358
        Good       0.82      1.00      0.90      2333

    accuracy                           0.86      3691
   macro avg       0.91      0.81      0.83      3691
weighted avg       0.89      0.86      0.85      3691

tl-vgg16-rms-prop-model_14.h5


/tmp/ipykernel_52851/2584673372.py:18: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  Y_pred = model.predict_generator(imgen, num_of_test_samples)


[[0.99999994 0.        ]
 [0.99999994 0.        ]
 [0.         0.99999994]
 ...
 [0.         1.        ]
 [0.         1.        ]
 [0.         1.        ]]
Confusion Matrix
[[ 941  417]
 [   0 2333]]
Classification Report
              precision    recall  f1-score   support

         Bad       1.00      0.69      0.82      1358
        Good       0.85      1.00      0.92      2333

    accuracy                           0.89      3691
   macro avg       0.92      0.85      0.87      3691
weighted avg       0.90      0.89      0.88      3691

tl-vgg16-rms-prop-model_17.h5


/tmp/ipykernel_52851/2584673372.py:18: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  Y_pred = model.predict_generator(imgen, num_of_test_samples)


[[0.99999994 0.        ]
 [0.         0.99999994]
 [0.         0.99999994]
 ...
 [0.         1.        ]
 [0.         1.        ]
 [0.         1.        ]]
Confusion Matrix
[[ 719  639]
 [   0 2333]]
Classification Report
              precision    recall  f1-score   support

         Bad       1.00      0.53      0.69      1358
        Good       0.78      1.00      0.88      2333

    accuracy                           0.83      3691
   macro avg       0.89      0.76      0.79      3691
weighted avg       0.86      0.83      0.81      3691

tl-vgg16-rms-prop-model_19.h5


/tmp/ipykernel_52851/2584673372.py:18: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  Y_pred = model.predict_generator(imgen, num_of_test_samples)


[[0.99999994 0.        ]
 [0.         0.99999994]
 [0.         0.99999994]
 ...
 [0.         1.        ]
 [0.         1.        ]
 [0.         1.        ]]
Confusion Matrix
[[ 718  640]
 [   0 2333]]
Classification Report
              precision    recall  f1-score   support

         Bad       1.00      0.53      0.69      1358
        Good       0.78      1.00      0.88      2333

    accuracy                           0.83      3691
   macro avg       0.89      0.76      0.79      3691
weighted avg       0.86      0.83      0.81      3691

tl-vgg16-rms-prop-model_06.h5


/tmp/ipykernel_52851/2584673372.py:18: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  Y_pred = model.predict_generator(imgen, num_of_test_samples)


[[0.99999994 0.        ]
 [0.         0.99999994]
 [0.         0.99999994]
 ...
 [0.         1.        ]
 [0.         1.        ]
 [0.         1.        ]]
Confusion Matrix
[[ 512  846]
 [   0 2333]]
Classification Report
              precision    recall  f1-score   support

         Bad       1.00      0.38      0.55      1358
        Good       0.73      1.00      0.85      2333

    accuracy                           0.77      3691
   macro avg       0.87      0.69      0.70      3691
weighted avg       0.83      0.77      0.74      3691

tl-vgg16-rms-prop-model_20.h5


/tmp/ipykernel_52851/2584673372.py:18: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  Y_pred = model.predict_generator(imgen, num_of_test_samples)


[[0.99999994 0.        ]
 [0.         0.99999994]
 [0.         0.99999994]
 ...
 [0.         1.        ]
 [0.         1.        ]
 [0.         1.        ]]
Confusion Matrix
[[ 718  640]
 [   0 2333]]
Classification Report
              precision    recall  f1-score   support

         Bad       1.00      0.53      0.69      1358
        Good       0.78      1.00      0.88      2333

    accuracy                           0.83      3691
   macro avg       0.89      0.76      0.79      3691
weighted avg       0.86      0.83      0.81      3691

tl-vgg16-rms-prop-model_03.h5


/tmp/ipykernel_52851/2584673372.py:18: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  Y_pred = model.predict_generator(imgen, num_of_test_samples)


[[0.99999994 0.        ]
 [0.99999994 0.        ]
 [0.         0.99999994]
 ...
 [0.         1.        ]
 [0.         1.        ]
 [0.         1.        ]]
Confusion Matrix
[[ 880  478]
 [   1 2332]]
Classification Report
              precision    recall  f1-score   support

         Bad       1.00      0.65      0.79      1358
        Good       0.83      1.00      0.91      2333

    accuracy                           0.87      3691
   macro avg       0.91      0.82      0.85      3691
weighted avg       0.89      0.87      0.86      3691

tl-vgg16-rms-prop-model_18.h5


/tmp/ipykernel_52851/2584673372.py:18: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  Y_pred = model.predict_generator(imgen, num_of_test_samples)


[[0.99999994 0.        ]
 [0.         0.99999994]
 [0.         0.99999994]
 ...
 [0.         1.        ]
 [0.         1.        ]
 [0.         1.        ]]
Confusion Matrix
[[ 719  639]
 [   0 2333]]
Classification Report
              precision    recall  f1-score   support

         Bad       1.00      0.53      0.69      1358
        Good       0.78      1.00      0.88      2333

    accuracy                           0.83      3691
   macro avg       0.89      0.76      0.79      3691
weighted avg       0.86      0.83      0.81      3691

tl-vgg16-rms-prop-model_08.h5


/tmp/ipykernel_52851/2584673372.py:18: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  Y_pred = model.predict_generator(imgen, num_of_test_samples)


[[0.99999994 0.        ]
 [0.         0.99999994]
 [0.         0.99999994]
 ...
 [0.         1.        ]
 [0.         1.        ]
 [0.         1.        ]]
Confusion Matrix
[[ 737  621]
 [   0 2333]]
Classification Report
              precision    recall  f1-score   support

         Bad       1.00      0.54      0.70      1358
        Good       0.79      1.00      0.88      2333

    accuracy                           0.83      3691
   macro avg       0.89      0.77      0.79      3691
weighted avg       0.87      0.83      0.82      3691

tl-vgg16-rms-prop-model_01.h5


/tmp/ipykernel_52851/2584673372.py:18: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  Y_pred = model.predict_generator(imgen, num_of_test_samples)


[[0.99999994 0.        ]
 [0.99999994 0.        ]
 [0.         0.99999994]
 ...
 [0.         1.        ]
 [0.         1.        ]
 [0.         1.        ]]
Confusion Matrix
[[1025  333]
 [   1 2332]]
Classification Report
              precision    recall  f1-score   support

         Bad       1.00      0.75      0.86      1358
        Good       0.88      1.00      0.93      2333

    accuracy                           0.91      3691
   macro avg       0.94      0.88      0.90      3691
weighted avg       0.92      0.91      0.91      3691

tl-vgg16-rms-prop-model_16.h5


/tmp/ipykernel_52851/2584673372.py:18: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  Y_pred = model.predict_generator(imgen, num_of_test_samples)


[[0.99999994 0.        ]
 [0.99999994 0.        ]
 [0.         0.99999994]
 ...
 [0.         1.        ]
 [0.         1.        ]
 [0.         1.        ]]
Confusion Matrix
[[ 847  511]
 [   0 2333]]
Classification Report
              precision    recall  f1-score   support

         Bad       1.00      0.62      0.77      1358
        Good       0.82      1.00      0.90      2333

    accuracy                           0.86      3691
   macro avg       0.91      0.81      0.83      3691
weighted avg       0.89      0.86      0.85      3691



## Bad

In [3]:
import os
from keras.models import Model
from tensorflow.keras.optimizers import Adam
from keras.applications.vgg16 import VGG16, preprocess_input
from keras.preprocessing.image import ImageDataGenerator
from keras.callbacks import ModelCheckpoint, EarlyStopping
from keras.layers import Dense, Dropout, Flatten
from pathlib import Path
import numpy as np


import keras


BATCH_SIZE = 10
test_data_dir = f'all_data_quality/bad/test'
test_generator = ImageDataGenerator(preprocessing_function=preprocess_input)
testgen = test_generator.flow_from_directory(test_data_dir,
                                             target_size=(224, 224),
                                             class_mode='categorical',
                                             batch_size=BATCH_SIZE,
                                             shuffle=False,
                                             seed=42)


quality_model_file = f'model-all-data-quality-bad'
model_quality_path = Path(quality_model_file)
for model_name in model_quality_path.glob('*model_*'):
    print(model_name.name)
    evaluate(model_name=model_name, imgen=testgen, batch_size=BATCH_SIZE)

Found 1357 images belonging to 6 classes.
tl-vgg16-rms-prop-model_02.h5


2022-09-24 17:48:11.607896: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2022-09-24 17:48:11.607949: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (ankan): /proc/driver/nvidia/version does not exist
2022-09-24 17:48:11.622663: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
/tmp/ipykernel_5889/2584673372.py:18: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  Y_pred = model.predict_generator(imgen, num_of_test_samples)


[[0.99999994 0.         0.         0.         0.         0.        ]
 [0.99999994 0.         0.         0.         0.         0.        ]
 [0.99999994 0.         0.         0.         0.         0.        ]
 ...
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]]
Confusion Matrix
[[225   0   1   1   0   1]
 [  1 214   0   0   0   2]
 [  0   0 221   1   0   4]
 [  0   1   3 204   6   3]
 [ 30   0   0   3 193   6]
 [  2   0   5   0   1 229]]
Classification Report
                 precision    recall  f1-score   support

      Apple_Bad       0.87      0.99      0.93       228
     Banana_Bad       1.00      0.99      0.99       217
      Guava_Bad       0.96      0.98      0.97       226
       Lime_Bad       0.98      0.94      0.96       217
     Orange_Bad       0.96      0.83      0.89       232
Pomegranate_Bad       0.93      0.9

/tmp/ipykernel_5889/2584673372.py:18: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  Y_pred = model.predict_generator(imgen, num_of_test_samples)


[[0.99999994 0.         0.         0.         0.         0.        ]
 [0.99999994 0.         0.         0.         0.         0.        ]
 [0.99999994 0.         0.         0.         0.         0.        ]
 ...
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]]
Confusion Matrix
[[213   0   2   2   4   7]
 [  0 215   0   0   0   2]
 [  0   0 205   4   1  16]
 [  1   1   2 212   1   0]
 [  6   0   1   6 207  12]
 [  0   0   2   0   1 234]]
Classification Report
                 precision    recall  f1-score   support

      Apple_Bad       0.97      0.93      0.95       228
     Banana_Bad       1.00      0.99      0.99       217
      Guava_Bad       0.97      0.91      0.94       226
       Lime_Bad       0.95      0.98      0.96       217
     Orange_Bad       0.97      0.89      0.93       232
Pomegranate_Bad       0.86      0.9

/tmp/ipykernel_5889/2584673372.py:18: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  Y_pred = model.predict_generator(imgen, num_of_test_samples)


[[0.99999994 0.         0.         0.         0.         0.        ]
 [0.99999994 0.         0.         0.         0.         0.        ]
 [0.99999994 0.         0.         0.         0.         0.        ]
 ...
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]]
Confusion Matrix
[[221   0   1   2   2   2]
 [  0 215   0   0   0   2]
 [  1   0 213   6   0   6]
 [  1   1   2 213   0   0]
 [ 31   1   1   8 186   5]
 [  0   0   3   1   2 231]]
Classification Report
                 precision    recall  f1-score   support

      Apple_Bad       0.87      0.97      0.92       228
     Banana_Bad       0.99      0.99      0.99       217
      Guava_Bad       0.97      0.94      0.96       226
       Lime_Bad       0.93      0.98      0.95       217
     Orange_Bad       0.98      0.80      0.88       232
Pomegranate_Bad       0.94      0.9

/tmp/ipykernel_5889/2584673372.py:18: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  Y_pred = model.predict_generator(imgen, num_of_test_samples)


[[0.99999994 0.         0.         0.         0.         0.        ]
 [0.99999994 0.         0.         0.         0.         0.        ]
 [0.99999994 0.         0.         0.         0.         0.        ]
 ...
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]]
Confusion Matrix
[[221   0   1   2   2   2]
 [  0 215   0   0   0   2]
 [  1   0 213   6   0   6]
 [  1   1   2 213   0   0]
 [ 31   1   1   8 186   5]
 [  0   0   3   1   2 231]]
Classification Report
                 precision    recall  f1-score   support

      Apple_Bad       0.87      0.97      0.92       228
     Banana_Bad       0.99      0.99      0.99       217
      Guava_Bad       0.97      0.94      0.96       226
       Lime_Bad       0.93      0.98      0.95       217
     Orange_Bad       0.98      0.80      0.88       232
Pomegranate_Bad       0.94      0.9

/tmp/ipykernel_5889/2584673372.py:18: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  Y_pred = model.predict_generator(imgen, num_of_test_samples)


[[0.99999994 0.         0.         0.         0.         0.        ]
 [0.99999994 0.         0.         0.         0.         0.        ]
 [0.99999994 0.         0.         0.         0.         0.        ]
 ...
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]]
Confusion Matrix
[[221   0   1   2   2   2]
 [  0 215   0   0   0   2]
 [  1   0 213   6   0   6]
 [  1   1   2 213   0   0]
 [ 31   1   1   8 186   5]
 [  0   0   3   1   2 231]]
Classification Report
                 precision    recall  f1-score   support

      Apple_Bad       0.87      0.97      0.92       228
     Banana_Bad       0.99      0.99      0.99       217
      Guava_Bad       0.97      0.94      0.96       226
       Lime_Bad       0.93      0.98      0.95       217
     Orange_Bad       0.98      0.80      0.88       232
Pomegranate_Bad       0.94      0.9

/tmp/ipykernel_5889/2584673372.py:18: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  Y_pred = model.predict_generator(imgen, num_of_test_samples)


[[0.99999994 0.         0.         0.         0.         0.        ]
 [0.99999994 0.         0.         0.         0.         0.        ]
 [0.99999994 0.         0.         0.         0.         0.        ]
 ...
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]]
Confusion Matrix
[[222   0   0   2   2   2]
 [  0 215   0   0   0   2]
 [  1   0 214   5   0   6]
 [  1   1   2 213   0   0]
 [ 33   1   1   8 184   5]
 [  0   0   3   1   2 231]]
Classification Report
                 precision    recall  f1-score   support

      Apple_Bad       0.86      0.97      0.92       228
     Banana_Bad       0.99      0.99      0.99       217
      Guava_Bad       0.97      0.95      0.96       226
       Lime_Bad       0.93      0.98      0.96       217
     Orange_Bad       0.98      0.79      0.88       232
Pomegranate_Bad       0.94      0.9

/tmp/ipykernel_5889/2584673372.py:18: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  Y_pred = model.predict_generator(imgen, num_of_test_samples)


[[0.99999994 0.         0.         0.         0.         0.        ]
 [0.99999994 0.         0.         0.         0.         0.        ]
 [0.99999994 0.         0.         0.         0.         0.        ]
 ...
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]]
Confusion Matrix
[[222   0   0   2   2   2]
 [  0 215   0   0   0   2]
 [  1   0 213   6   0   6]
 [  1   1   2 213   0   0]
 [ 31   1   1   8 186   5]
 [  0   0   3   1   2 231]]
Classification Report
                 precision    recall  f1-score   support

      Apple_Bad       0.87      0.97      0.92       228
     Banana_Bad       0.99      0.99      0.99       217
      Guava_Bad       0.97      0.94      0.96       226
       Lime_Bad       0.93      0.98      0.95       217
     Orange_Bad       0.98      0.80      0.88       232
Pomegranate_Bad       0.94      0.9

/tmp/ipykernel_5889/2584673372.py:18: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  Y_pred = model.predict_generator(imgen, num_of_test_samples)


[[0.99999994 0.         0.         0.         0.         0.        ]
 [0.99999994 0.         0.         0.         0.         0.        ]
 [0.99999994 0.         0.         0.         0.         0.        ]
 ...
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]]
Confusion Matrix
[[222   0   0   2   2   2]
 [  0 215   0   0   0   2]
 [  1   0 213   6   0   6]
 [  1   1   2 213   0   0]
 [ 31   1   1   8 186   5]
 [  0   0   3   1   2 231]]
Classification Report
                 precision    recall  f1-score   support

      Apple_Bad       0.87      0.97      0.92       228
     Banana_Bad       0.99      0.99      0.99       217
      Guava_Bad       0.97      0.94      0.96       226
       Lime_Bad       0.93      0.98      0.95       217
     Orange_Bad       0.98      0.80      0.88       232
Pomegranate_Bad       0.94      0.9

/tmp/ipykernel_5889/2584673372.py:18: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  Y_pred = model.predict_generator(imgen, num_of_test_samples)


[[0.99999994 0.         0.         0.         0.         0.        ]
 [0.99999994 0.         0.         0.         0.         0.        ]
 [0.99999994 0.         0.         0.         0.         0.        ]
 ...
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]]
Confusion Matrix
[[222   0   0   2   2   2]
 [  0 215   0   0   0   2]
 [  1   0 213   6   0   6]
 [  1   1   2 213   0   0]
 [ 31   1   1   8 186   5]
 [  0   0   3   1   2 231]]
Classification Report
                 precision    recall  f1-score   support

      Apple_Bad       0.87      0.97      0.92       228
     Banana_Bad       0.99      0.99      0.99       217
      Guava_Bad       0.97      0.94      0.96       226
       Lime_Bad       0.93      0.98      0.95       217
     Orange_Bad       0.98      0.80      0.88       232
Pomegranate_Bad       0.94      0.9

/tmp/ipykernel_5889/2584673372.py:18: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  Y_pred = model.predict_generator(imgen, num_of_test_samples)


[[0.99999994 0.         0.         0.         0.         0.        ]
 [0.99999994 0.         0.         0.         0.         0.        ]
 [0.99999994 0.         0.         0.         0.         0.        ]
 ...
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]]
Confusion Matrix
[[221   0   1   2   2   2]
 [  0 215   0   0   0   2]
 [  1   0 213   6   0   6]
 [  1   1   2 213   0   0]
 [ 31   1   1   8 186   5]
 [  0   0   3   1   2 231]]
Classification Report
                 precision    recall  f1-score   support

      Apple_Bad       0.87      0.97      0.92       228
     Banana_Bad       0.99      0.99      0.99       217
      Guava_Bad       0.97      0.94      0.96       226
       Lime_Bad       0.93      0.98      0.95       217
     Orange_Bad       0.98      0.80      0.88       232
Pomegranate_Bad       0.94      0.9

/tmp/ipykernel_5889/2584673372.py:18: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  Y_pred = model.predict_generator(imgen, num_of_test_samples)


[[0.99999994 0.         0.         0.         0.         0.        ]
 [0.99999994 0.         0.         0.         0.         0.        ]
 [0.99999994 0.         0.         0.         0.         0.        ]
 ...
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]]
Confusion Matrix
[[221   0   1   2   2   2]
 [  0 215   0   0   0   2]
 [  1   0 213   6   0   6]
 [  1   1   2 213   0   0]
 [ 31   1   1   8 186   5]
 [  0   0   3   1   2 231]]
Classification Report
                 precision    recall  f1-score   support

      Apple_Bad       0.87      0.97      0.92       228
     Banana_Bad       0.99      0.99      0.99       217
      Guava_Bad       0.97      0.94      0.96       226
       Lime_Bad       0.93      0.98      0.95       217
     Orange_Bad       0.98      0.80      0.88       232
Pomegranate_Bad       0.94      0.9

/tmp/ipykernel_5889/2584673372.py:18: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  Y_pred = model.predict_generator(imgen, num_of_test_samples)


[[0.99999994 0.         0.         0.         0.         0.        ]
 [0.99999994 0.         0.         0.         0.         0.        ]
 [0.99999994 0.         0.         0.         0.         0.        ]
 ...
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]]
Confusion Matrix
[[221   0   1   2   2   2]
 [  0 215   0   0   0   2]
 [  1   0 213   6   0   6]
 [  1   1   2 213   0   0]
 [ 31   1   1   8 186   5]
 [  0   0   3   1   2 231]]
Classification Report
                 precision    recall  f1-score   support

      Apple_Bad       0.87      0.97      0.92       228
     Banana_Bad       0.99      0.99      0.99       217
      Guava_Bad       0.97      0.94      0.96       226
       Lime_Bad       0.93      0.98      0.95       217
     Orange_Bad       0.98      0.80      0.88       232
Pomegranate_Bad       0.94      0.9

/tmp/ipykernel_5889/2584673372.py:18: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  Y_pred = model.predict_generator(imgen, num_of_test_samples)


[[0.99999994 0.         0.         0.         0.         0.        ]
 [0.99999994 0.         0.         0.         0.         0.        ]
 [0.99999994 0.         0.         0.         0.         0.        ]
 ...
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]]
Confusion Matrix
[[221   0   1   2   2   2]
 [  0 215   0   0   0   2]
 [  1   0 213   6   0   6]
 [  1   1   2 213   0   0]
 [ 31   1   1   8 186   5]
 [  0   0   3   1   2 231]]
Classification Report
                 precision    recall  f1-score   support

      Apple_Bad       0.87      0.97      0.92       228
     Banana_Bad       0.99      0.99      0.99       217
      Guava_Bad       0.97      0.94      0.96       226
       Lime_Bad       0.93      0.98      0.95       217
     Orange_Bad       0.98      0.80      0.88       232
Pomegranate_Bad       0.94      0.9

ValueError: No model config found in the file at <tensorflow.python.platform.gfile.GFile object at 0x7fc47aec5780>.

In [4]:
import os
from keras.models import Model
from tensorflow.keras.optimizers import Adam
from keras.applications.vgg16 import VGG16, preprocess_input
from keras.preprocessing.image import ImageDataGenerator
from keras.callbacks import ModelCheckpoint, EarlyStopping
from keras.layers import Dense, Dropout, Flatten
from pathlib import Path
import numpy as np


import keras


BATCH_SIZE = 10
test_data_dir = f'all_data_quality/good/test'
test_generator = ImageDataGenerator(preprocessing_function=preprocess_input)
testgen = test_generator.flow_from_directory(test_data_dir,
                                             target_size=(224, 224),
                                             class_mode='categorical',
                                             batch_size=BATCH_SIZE,
                                             shuffle=False,
                                             seed=42)


quality_model_file = f'model-all-data-quality-good'
model_quality_path = Path(quality_model_file)
for model_name in model_quality_path.glob('*model_*'):
    print(model_name.name)
    evaluate(model_name=model_name, imgen=testgen, batch_size=BATCH_SIZE)

Found 2333 images belonging to 6 classes.
tl-vgg16-rms-prop-model_02.h5


/tmp/ipykernel_5889/2584673372.py:18: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  Y_pred = model.predict_generator(imgen, num_of_test_samples)


[[0.99999994 0.         0.         0.         0.         0.        ]
 [0.99999994 0.         0.         0.         0.         0.        ]
 [0.99999994 0.         0.         0.         0.         0.        ]
 ...
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]]
Confusion Matrix
[[ 227    3    0    0    0    0]
 [   0  222    1    0    0    0]
 [   6    0  223    0    1    0]
 [   4    0    3  212    0    0]
 [  49    0    4    9  177    4]
 [  40    0   21    4    2 1121]]
Classification Report
                  precision    recall  f1-score   support

      Apple_Good       0.70      0.99      0.82       230
     Banana_Good       0.99      1.00      0.99       223
      Guava_Good       0.88      0.97      0.93       230
       Lime_Good       0.94      0.97      0.95       219
     Orange_Good       0.98      0.73      0.84    

/tmp/ipykernel_5889/2584673372.py:18: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  Y_pred = model.predict_generator(imgen, num_of_test_samples)


[[0.99999994 0.         0.         0.         0.         0.        ]
 [0.99999994 0.         0.         0.         0.         0.        ]
 [0.99999994 0.         0.         0.         0.         0.        ]
 ...
 [0.         0.         0.         0.         1.         0.        ]
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]]
Confusion Matrix
[[ 224    2    1    0    2    1]
 [   0  223    0    0    0    0]
 [   5    0  221    1    3    0]
 [   5    0    1  213    0    0]
 [   7    0    0    2  234    0]
 [  15    0    5    1    3 1164]]
Classification Report
                  precision    recall  f1-score   support

      Apple_Good       0.88      0.97      0.92       230
     Banana_Good       0.99      1.00      1.00       223
      Guava_Good       0.97      0.96      0.97       230
       Lime_Good       0.98      0.97      0.98       219
     Orange_Good       0.97      0.96      0.96    

/tmp/ipykernel_5889/2584673372.py:18: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  Y_pred = model.predict_generator(imgen, num_of_test_samples)


[[0.99999994 0.         0.         0.         0.         0.        ]
 [0.99999994 0.         0.         0.         0.         0.        ]
 [0.99999994 0.         0.         0.         0.         0.        ]
 ...
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]]
Confusion Matrix
[[ 213    2    8    0    5    2]
 [   0  222    1    0    0    0]
 [   3    0  226    0    1    0]
 [   6    2    3  208    0    0]
 [  15    0   16    1  209    2]
 [   5    0    8    0    1 1174]]
Classification Report
                  precision    recall  f1-score   support

      Apple_Good       0.88      0.93      0.90       230
     Banana_Good       0.98      1.00      0.99       223
      Guava_Good       0.86      0.98      0.92       230
       Lime_Good       1.00      0.95      0.97       219
     Orange_Good       0.97      0.86      0.91    

/tmp/ipykernel_5889/2584673372.py:18: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  Y_pred = model.predict_generator(imgen, num_of_test_samples)


[[0.99999994 0.         0.         0.         0.         0.        ]
 [0.99999994 0.         0.         0.         0.         0.        ]
 [0.99999994 0.         0.         0.         0.         0.        ]
 ...
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]]
Confusion Matrix
[[ 213    2    8    0    5    2]
 [   0  222    1    0    0    0]
 [   3    0  226    0    1    0]
 [   6    2    3  208    0    0]
 [  15    0   16    1  209    2]
 [   5    0    8    0    1 1174]]
Classification Report
                  precision    recall  f1-score   support

      Apple_Good       0.88      0.93      0.90       230
     Banana_Good       0.98      1.00      0.99       223
      Guava_Good       0.86      0.98      0.92       230
       Lime_Good       1.00      0.95      0.97       219
     Orange_Good       0.97      0.86      0.91    

/tmp/ipykernel_5889/2584673372.py:18: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  Y_pred = model.predict_generator(imgen, num_of_test_samples)


[[0.99999994 0.         0.         0.         0.         0.        ]
 [0.99999994 0.         0.         0.         0.         0.        ]
 [0.99999994 0.         0.         0.         0.         0.        ]
 ...
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]]
Confusion Matrix
[[ 213    2    8    0    5    2]
 [   0  222    1    0    0    0]
 [   3    0  226    0    1    0]
 [   6    2    3  208    0    0]
 [  15    0   16    1  209    2]
 [   5    0    8    0    1 1174]]
Classification Report
                  precision    recall  f1-score   support

      Apple_Good       0.88      0.93      0.90       230
     Banana_Good       0.98      1.00      0.99       223
      Guava_Good       0.86      0.98      0.92       230
       Lime_Good       1.00      0.95      0.97       219
     Orange_Good       0.97      0.86      0.91    

/tmp/ipykernel_5889/2584673372.py:18: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  Y_pred = model.predict_generator(imgen, num_of_test_samples)


[[0.99999994 0.         0.         0.         0.         0.        ]
 [0.99999994 0.         0.         0.         0.         0.        ]
 [0.99999994 0.         0.         0.         0.         0.        ]
 ...
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]]
Confusion Matrix
[[ 216    3    3    0    8    0]
 [   0  223    0    0    0    0]
 [   3    0  223    1    3    0]
 [   2    0    3  213    1    0]
 [   5    0    3    0  233    2]
 [  10    0    0    0    0 1178]]
Classification Report
                  precision    recall  f1-score   support

      Apple_Good       0.92      0.94      0.93       230
     Banana_Good       0.99      1.00      0.99       223
      Guava_Good       0.96      0.97      0.97       230
       Lime_Good       1.00      0.97      0.98       219
     Orange_Good       0.95      0.96      0.95    

/tmp/ipykernel_5889/2584673372.py:18: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  Y_pred = model.predict_generator(imgen, num_of_test_samples)


[[0.99999994 0.         0.         0.         0.         0.        ]
 [0.99999994 0.         0.         0.         0.         0.        ]
 [0.99999994 0.         0.         0.         0.         0.        ]
 ...
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]]
Confusion Matrix
[[ 213    2    8    0    5    2]
 [   0  222    1    0    0    0]
 [   3    0  226    0    1    0]
 [   6    2    3  208    0    0]
 [  15    0   16    1  209    2]
 [   5    0    8    0    1 1174]]
Classification Report
                  precision    recall  f1-score   support

      Apple_Good       0.88      0.93      0.90       230
     Banana_Good       0.98      1.00      0.99       223
      Guava_Good       0.86      0.98      0.92       230
       Lime_Good       1.00      0.95      0.97       219
     Orange_Good       0.97      0.86      0.91    

/tmp/ipykernel_5889/2584673372.py:18: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  Y_pred = model.predict_generator(imgen, num_of_test_samples)


[[0.99999994 0.         0.         0.         0.         0.        ]
 [0.         0.         0.99999994 0.         0.         0.        ]
 [0.99999994 0.         0.         0.         0.         0.        ]
 ...
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]]
Confusion Matrix
[[ 211    2   13    0    4    0]
 [   0  223    0    0    0    0]
 [   3    0  226    0    1    0]
 [   5    2    2  210    0    0]
 [  10    0   14    1  216    2]
 [   5    0    8    0    1 1174]]
Classification Report
                  precision    recall  f1-score   support

      Apple_Good       0.90      0.92      0.91       230
     Banana_Good       0.98      1.00      0.99       223
      Guava_Good       0.86      0.98      0.92       230
       Lime_Good       1.00      0.96      0.98       219
     Orange_Good       0.97      0.89      0.93    

/tmp/ipykernel_5889/2584673372.py:18: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  Y_pred = model.predict_generator(imgen, num_of_test_samples)


[[0.99999994 0.         0.         0.         0.         0.        ]
 [0.99999994 0.         0.         0.         0.         0.        ]
 [0.99999994 0.         0.         0.         0.         0.        ]
 ...
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]]
Confusion Matrix
[[ 224    2    3    0    1    0]
 [   1  221    1    0    0    0]
 [   5    0  224    0    1    0]
 [  13    0    1  205    0    0]
 [  15    0    5    0  223    0]
 [  20    0   21    0   11 1136]]
Classification Report
                  precision    recall  f1-score   support

      Apple_Good       0.81      0.97      0.88       230
     Banana_Good       0.99      0.99      0.99       223
      Guava_Good       0.88      0.97      0.92       230
       Lime_Good       1.00      0.94      0.97       219
     Orange_Good       0.94      0.92      0.93    

/tmp/ipykernel_5889/2584673372.py:18: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  Y_pred = model.predict_generator(imgen, num_of_test_samples)


[[0.99999994 0.         0.         0.         0.         0.        ]
 [0.99999994 0.         0.         0.         0.         0.        ]
 [0.99999994 0.         0.         0.         0.         0.        ]
 ...
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]]
Confusion Matrix
[[ 213    2    8    0    5    2]
 [   0  222    1    0    0    0]
 [   3    0  226    0    1    0]
 [   6    2    3  208    0    0]
 [  15    0   16    1  209    2]
 [   5    0    8    0    1 1174]]
Classification Report
                  precision    recall  f1-score   support

      Apple_Good       0.88      0.93      0.90       230
     Banana_Good       0.98      1.00      0.99       223
      Guava_Good       0.86      0.98      0.92       230
       Lime_Good       1.00      0.95      0.97       219
     Orange_Good       0.97      0.86      0.91    

/tmp/ipykernel_5889/2584673372.py:18: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  Y_pred = model.predict_generator(imgen, num_of_test_samples)


[[0.99999994 0.         0.         0.         0.         0.        ]
 [0.99999994 0.         0.         0.         0.         0.        ]
 [0.99999994 0.         0.         0.         0.         0.        ]
 ...
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]]
Confusion Matrix
[[ 213    2    8    0    5    2]
 [   0  222    1    0    0    0]
 [   3    0  226    0    1    0]
 [   6    2    3  208    0    0]
 [  15    0   16    1  209    2]
 [   5    0    8    0    1 1174]]
Classification Report
                  precision    recall  f1-score   support

      Apple_Good       0.88      0.93      0.90       230
     Banana_Good       0.98      1.00      0.99       223
      Guava_Good       0.86      0.98      0.92       230
       Lime_Good       1.00      0.95      0.97       219
     Orange_Good       0.97      0.86      0.91    

/tmp/ipykernel_5889/2584673372.py:18: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  Y_pred = model.predict_generator(imgen, num_of_test_samples)


[[0.99999994 0.         0.         0.         0.         0.        ]
 [0.99999994 0.         0.         0.         0.         0.        ]
 [0.99999994 0.         0.         0.         0.         0.        ]
 ...
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]]
Confusion Matrix
[[ 213    2    8    0    5    2]
 [   0  222    1    0    0    0]
 [   3    0  226    0    1    0]
 [   6    2    3  208    0    0]
 [  15    0   16    1  209    2]
 [   5    0    8    0    1 1174]]
Classification Report
                  precision    recall  f1-score   support

      Apple_Good       0.88      0.93      0.90       230
     Banana_Good       0.98      1.00      0.99       223
      Guava_Good       0.86      0.98      0.92       230
       Lime_Good       1.00      0.95      0.97       219
     Orange_Good       0.97      0.86      0.91    

/tmp/ipykernel_5889/2584673372.py:18: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  Y_pred = model.predict_generator(imgen, num_of_test_samples)


[[0.99999994 0.         0.         0.         0.         0.        ]
 [0.99999994 0.         0.         0.         0.         0.        ]
 [0.99999994 0.         0.         0.         0.         0.        ]
 ...
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]]
Confusion Matrix
[[ 213    2    8    0    5    2]
 [   0  222    1    0    0    0]
 [   3    0  226    0    1    0]
 [   6    2    3  208    0    0]
 [  15    0   16    1  209    2]
 [   5    0    8    0    1 1174]]
Classification Report
                  precision    recall  f1-score   support

      Apple_Good       0.88      0.93      0.90       230
     Banana_Good       0.98      1.00      0.99       223
      Guava_Good       0.86      0.98      0.92       230
       Lime_Good       1.00      0.95      0.97       219
     Orange_Good       0.97      0.86      0.91    

/tmp/ipykernel_5889/2584673372.py:18: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  Y_pred = model.predict_generator(imgen, num_of_test_samples)


[[0.99999994 0.         0.         0.         0.         0.        ]
 [0.99999994 0.         0.         0.         0.         0.        ]
 [0.99999994 0.         0.         0.         0.         0.        ]
 ...
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]]
Confusion Matrix
[[ 220    2    2    0    6    0]
 [   0  222    1    0    0    0]
 [   3    0  224    0    3    0]
 [   6    0    2  198   13    0]
 [   6    0    3    0  233    1]
 [   5    0    2    0    2 1179]]
Classification Report
                  precision    recall  f1-score   support

      Apple_Good       0.92      0.96      0.94       230
     Banana_Good       0.99      1.00      0.99       223
      Guava_Good       0.96      0.97      0.97       230
       Lime_Good       1.00      0.90      0.95       219
     Orange_Good       0.91      0.96      0.93    

/tmp/ipykernel_5889/2584673372.py:18: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  Y_pred = model.predict_generator(imgen, num_of_test_samples)


[[0.99999994 0.         0.         0.         0.         0.        ]
 [0.99999994 0.         0.         0.         0.         0.        ]
 [0.99999994 0.         0.         0.         0.         0.        ]
 ...
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]]
Confusion Matrix
[[ 213    2    8    0    5    2]
 [   0  222    1    0    0    0]
 [   3    0  226    0    1    0]
 [   6    2    3  208    0    0]
 [  15    0   16    1  209    2]
 [   5    0    8    0    1 1174]]
Classification Report
                  precision    recall  f1-score   support

      Apple_Good       0.88      0.93      0.90       230
     Banana_Good       0.98      1.00      0.99       223
      Guava_Good       0.86      0.98      0.92       230
       Lime_Good       1.00      0.95      0.97       219
     Orange_Good       0.97      0.86      0.91    

/tmp/ipykernel_5889/2584673372.py:18: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  Y_pred = model.predict_generator(imgen, num_of_test_samples)


[[0.99999994 0.         0.         0.         0.         0.        ]
 [0.         0.         0.99999994 0.         0.         0.        ]
 [0.         0.         0.99999994 0.         0.         0.        ]
 ...
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]]
Confusion Matrix
[[ 192    3   33    0    0    2]
 [   0  222    1    0    0    0]
 [   1    0  229    0    0    0]
 [   1    0    4  214    0    0]
 [   9    0   50    2  181    1]
 [   8    0    8    0    0 1172]]
Classification Report
                  precision    recall  f1-score   support

      Apple_Good       0.91      0.83      0.87       230
     Banana_Good       0.99      1.00      0.99       223
      Guava_Good       0.70      1.00      0.83       230
       Lime_Good       0.99      0.98      0.98       219
     Orange_Good       1.00      0.74      0.85    

/tmp/ipykernel_5889/2584673372.py:18: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  Y_pred = model.predict_generator(imgen, num_of_test_samples)


[[0.99999994 0.         0.         0.         0.         0.        ]
 [0.99999994 0.         0.         0.         0.         0.        ]
 [0.99999994 0.         0.         0.         0.         0.        ]
 ...
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]]
Confusion Matrix
[[ 213    2    8    0    5    2]
 [   0  222    1    0    0    0]
 [   3    0  226    0    1    0]
 [   6    2    3  208    0    0]
 [  15    0   16    1  209    2]
 [   5    0    8    0    1 1174]]
Classification Report
                  precision    recall  f1-score   support

      Apple_Good       0.88      0.93      0.90       230
     Banana_Good       0.98      1.00      0.99       223
      Guava_Good       0.86      0.98      0.92       230
       Lime_Good       1.00      0.95      0.97       219
     Orange_Good       0.97      0.86      0.91    

/tmp/ipykernel_5889/2584673372.py:18: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  Y_pred = model.predict_generator(imgen, num_of_test_samples)


[[0.99999994 0.         0.         0.         0.         0.        ]
 [0.99999994 0.         0.         0.         0.         0.        ]
 [0.99999994 0.         0.         0.         0.         0.        ]
 ...
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]]
Confusion Matrix
[[ 215    2    2    0    8    3]
 [   0  223    0    0    0    0]
 [   1    0  226    0    3    0]
 [   1    2    1  210    5    0]
 [   5    2    1    0  234    1]
 [   5    0    0    0    2 1181]]
Classification Report
                  precision    recall  f1-score   support

      Apple_Good       0.95      0.93      0.94       230
     Banana_Good       0.97      1.00      0.99       223
      Guava_Good       0.98      0.98      0.98       230
       Lime_Good       1.00      0.96      0.98       219
     Orange_Good       0.93      0.96      0.95    

/tmp/ipykernel_5889/2584673372.py:18: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  Y_pred = model.predict_generator(imgen, num_of_test_samples)


[[9.9999994e-01 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  0.0000000e+00]
 [8.5765484e-32 0.0000000e+00 9.9999994e-01 0.0000000e+00 0.0000000e+00
  0.0000000e+00]
 [9.9999994e-01 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  0.0000000e+00]
 ...
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  1.0000000e+00]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  1.0000000e+00]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  1.0000000e+00]]
Confusion Matrix
[[ 171    3   20    1   33    2]
 [   0  222    1    0    0    0]
 [   1    0  219    2    8    0]
 [   0    0    1  190   28    0]
 [   0    0    3    2  238    0]
 [   3    0    5    0   23 1157]]
Classification Report
                  precision    recall  f1-score   support

      Apple_Good       0.98      0.74      0.84       230
     Banana_Good       0.99      1.00      0.99       223
      Guava_Good       0.88      0.95      0.91

/tmp/ipykernel_5889/2584673372.py:18: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  Y_pred = model.predict_generator(imgen, num_of_test_samples)


[[0.99999994 0.         0.         0.         0.         0.        ]
 [0.99999994 0.         0.         0.         0.         0.        ]
 [0.99999994 0.         0.         0.         0.         0.        ]
 ...
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         0.         0.         0.         1.        ]]
Confusion Matrix
[[ 213    2    8    0    5    2]
 [   0  222    1    0    0    0]
 [   3    0  226    0    1    0]
 [   6    2    3  208    0    0]
 [  15    0   16    1  209    2]
 [   5    0    8    0    1 1174]]
Classification Report
                  precision    recall  f1-score   support

      Apple_Good       0.88      0.93      0.90       230
     Banana_Good       0.98      1.00      0.99       223
      Guava_Good       0.86      0.98      0.92       230
       Lime_Good       1.00      0.95      0.97       219
     Orange_Good       0.97      0.86      0.91    